### ISSUE TITLE
Doesn't work from package.json

### ISSUE THREAD

**Issue by dangreen** [cheton/browserify-css#29]
```json
...
"browserify": {
    "transform": [
      [
        "babelify",
        {
          "presets": [
            "es2015",
            "stage-0",
            "react"
          ],
          "plugins": [
            [
              "transform-decorators-legacy"
            ]
          ]
        }
      ],
      [
        "style-templateify"
      ],
      [
        "browserify-css",
        {
          "global": true
        }
      ]
    ]
}
...
```

```
SyntaxError: 
/Users/dangreen/github/jam-editor/jam-editor/node_modules/cropper/dist/cropper.css:10
.cropper-container {
^
ParseError: Unexpected token
    at wrapWithPluginError (/Users/dangreen/github/jam-editor/jam-editor/node_modules/gulp-browserify/index.js:44:10)
    at Stream.<anonymous> (/Users/dangreen/github/jam-editor/jam-editor/node_modules/gulp-browserify/index.js:123:28)
    at Stream.<anonymous> (/Users/dangreen/github/jam-editor/jam-editor/node_modules/browserify/index.js:344:22)
    at Stream.<anonymous> (/Users/dangreen/github/jam-editor/jam-editor/node_modules/browserify/index.js:344:22)
    at emitOne (events.js:82:20)
    at Stream.emit (events.js:169:7)
    at Transform.onerror (/Users/dangreen/github/jam-editor/jam-editor/node_modules/stream-combiner/index.js:29:18)
    at emitOne (events.js:82:20)
    at Transform.emit (events.js:169:7)
    at onwriteError (/Users/dangreen/github/jam-editor/jam-editor/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:250:10)
    at onwrite (/Users/dangreen/github/jam-editor/jam-editor/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:268:5)
    at WritableState.onwrite (/Users/dangreen/github/jam-editor/jam-editor/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:106:5)
    at afterTransform (/Users/dangreen/github/jam-editor/jam-editor/node_modules/browserify/node_modules/readable-stream/lib/_stream_transform.js:104:5)
    at TransformState.afterTransform (/Users/dangreen/github/jam-editor/jam-editor/node_modules/browserify/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at Transform._transform (/Users/dangreen/github/jam-editor/jam-editor/node_modules/browserify/index.js:585:25)
    at Transform._read (/Users/dangreen/github/jam-editor/jam-editor/node_modules/browserify/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/Users/dangreen/github/jam-editor/jam-editor/node_modules/browserify/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/dangreen/github/jam-editor/jam-editor/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/dangreen/github/jam-editor/jam-editor/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/Users/dangreen/github/jam-editor/jam-editor/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:194
```

**Comment by cheton** [comment]
May I know if you're using gulp-browserify? It has been deprecated and not being supported for long time. Not sure if it was the reason. I will check it later.

**Comment by dangreen** [comment]
@cheton gulp-browserify is 100% not the reason.

**Comment by cheton** [comment]
It works well using the following configuration from both command line (i.e. `browserify src/index.js`) and `gulp-browserify`:

src/index.js
```js
import './index.css';

console.log('browserify-css test');
```

src/index.css
```css
body {
    background-color: #fff;
}
```

package.json
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "browserify": {
    "transform": [
      [
        "babelify",
        {
          "presets": [
            "es2015",
            "stage-0",
            "react"
          ]
        }
      ],
      [
        "browserify-css",
        {
          "rootDir": "src"
        }
      ]
    ]
  },
  "devDependencies": {
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "babelify": "^7.2.0",
    "browserify-css": "^0.8.4",
    "gulp": "^3.9.0",
    "gulp-browserify": "^0.5.1"
  }
}
```

**Comment by cheton** [comment]
May I know what you did in `style-templateify`? I cannot find it on npmjs.com.

**Comment by dangreen** [comment]
@cheton sorry, but i'm talking about `{ "global": true }`.

`react-cropper` package require style from `cropper` package with `browserify-css`: ["If you are using gulp, browserify or other build tools, make sure you enable global option true"](https://github.com/roadmanfong/react-cropper#browserify-user)

**Comment by cheton** [comment]
From browserify's documentation, it mentioned that you cannot configure global transforms in a package.json: https://github.com/substack/node-browserify#btransformtr-opts

So you only have two options, by specifying `-g` option from command line, or using browserify's api:

Option 1. Command Line:
```bash
browserify -g browserify-css src/index.js
```

Option 2. Browserify API:
```js
var gulp = require('gulp');
var browserify = require('browserify');
var source = require('vinyl-source-stream');
var buffer = require('vinyl-buffer');

gulp.task('default', function() {
    var b = browserify({ debug: true })
        .add('src/index.js')
        .transform('browserify-css', { global: true });

    b.bundle()
        .pipe(source('bundle.js'))
        .pipe(buffer())
        .pipe(gulp.dest('./build'));
});
```

The `gulp-browserify` plugin may have this kind of limitations because it read `package.json` as well and you were not able to call `b.transform('browserify-css', { global: true})` like that. It's recommended that you require `browserify` directly like the above example. It works by my side while building with `react-cropper`.

**Comment by dangreen** [comment]
@cheton ok, thanks!

**Comment by cheton** [comment]
Here is my `src/index.js` with above `gulpfile.js` example:

```js
var Cropper = require('react-cropper');
var Demo = React.createClass({
  _crop: function(){
    // image in dataUrl
    console.log(this.refs.cropper.getCroppedCanvas().toDataURL());
  },

  render: function() {
    return (
      <Cropper
        ref='cropper'
        src='http://fengyuanchen.github.io/cropper/img/picture.jpg'
        style={{height: 400, width: '100%'}}
        // Cropper.js options
        aspectRatio={16 / 9}
        guides={false}
        crop={this._crop} />
    );
  }
});
```
